language: ruby
rvm:
  - 2.1.0
  - 2.2.0
  - 2.3.3
  - 2.4.0
  - ruby-head

cache: bundler

before_install:
  - gem install bundler

matrix:
  allow_failures:
  - rvm: ruby-head

install:
  - bundle install
